### ISSUE TITLE
Order Status Update Emails

### ISSUE THREAD

**Issue by gahinton** [opencart/opencart#2576]
In version 2.0.1.1, emails are sent to the customer any time an order status is changed, even if Notify Customer is not selected.

**Comment by Tangol** [comment]
Same as https://github.com/opencart/opencart/issues/2572

**Comment by danielkerr** [comment]
yes the notify will s only if you leave a message.

if a customers order goes reversed he should know about it

**Comment by gahinton** [comment]
It is sending an email for EVERY update, even if Notify Customer is not selected and nothing is written. If I change from "Processing" to my "Preparing to Ship", I want it to update the history, but not send a email to the customer. When I change to "Shipped" they get an email (which I want). When I change to "Complete" they get another email (which they shouldn't). In 1.5 it didn't send anything unless I marked Notify Customer. I am having to disable the email when I change a status that I don't want the customers to get emailed on.

**Comment by danielkerr** [comment]
@gahinton

thats how you want the system to work! does not mean its a bug

emails should always go out on an order status change! again only comments should be private or not!

**Comment by sterrek** [comment]
It is sending an email for EVERY update, even if Notify Customer is not selected and nothing is written. If I change from "Processing" to my "Preparing to Ship", I want it to update the history, but not send a email to the customer. When I change to "Shipped" they get an email (which I want). When I change to "Complete" they get another email (which they shouldn't). In 1.5 it didn't send anything unless I marked Notify Customer. I am having to disable the email when I change a status that I don't want the customers to get emailed on. Thats not what we want ! i think this is an bug too

**Comment by dazzyweb** [comment]
I think that daniel will maybe change it. Look here: https://github.com/opencart/opencart/issues/2572

**Comment by gahinton** [comment]
Glad to see. I understand Daniel's point; however, I think depending on how it is used, in its current state, can send too many emails and aggravate a customer. For example, the system recognizes Complete as an order being totally finished so choosing this helps me to know an order is totally finished. If I have marked Shipped, and the customer has been emailed on this, they don't really care to get emailed again, especially if this is done back to back.
Maybe it could be set up so that the site owner can mark which settings automatically email the customer and which ones dont.

**Comment by IcarusDeve** [comment]
@gahinton @sterrek I believe it's a bug too. We use order statuses to check the order into different departments. It's not necessary for the client to be notified each and every time. Like 1.5x doesn't do that. I'm hoping this gets fixed ASAP. Very annoying for the customer.

**Comment by HOMEBRASIL** [comment]
version 2.0 is part of the error status change please help me following screen print with error

SyntaxError: Unexpected end of input
OK

update status order

**Comment by Sokonomi** [comment]
Anyone know of a way I can break this function? Its stupid.

**Comment by Dididan** [comment]
Still no solution on this issue ? I agree that this is very annoying (and stupid) ...   :(

**Comment by ainelena** [comment]
For those who struggles with same issue as me ("Notify customer" flag in order history makes no difference and system still sends out emails to customer on every status update), the manual fix is pretty easy:
file /catalog/model/checkout/order.php is doing that (even though you are changing status in Admin, change comes from catalog anyways).
in that file there is a function addOrderHistory, where close to the very end - around line 773 - there is a code that is commented like this:
// If order status is not 0 then send update text email
within this piece of code find a line that actually sends the email, it looks like this:
$mail->send();
and surround this line with an IF condition, so it now looks like this:
if ($notify) {
$mail->send();
}

After this change the status (or any other history) update will be send out as email to customer ONLY when flag "Notify Customer" is set.

**Comment by jkuusama** [comment]
@danielkerr Every time a system does something the user does not want, it is a bug. If the bug causes lost revenue, it is a very serious one. I think it is up to me to decide how I want to run my business, and I am very annoyed that OpenCart is spamming my customers; enough so, that I am losing them!

**Comment by Sokonomi** [comment]
I agree with Jkuusama, customer spam should be kept to a minimum.

My shop has a lot of internal status changes that are none of the customers concern (sent to engraver, sent to assembly, sent to packaging), so id rather not broadcast these. They are merely for my personnel to know where an order currently is. Only updates that directly involve the customer (Payment received, Ready for pickup, Shipped) should be sent out.

In fact I would love the option to save a "notify customer" setting for each status so it does it automatically!

**Comment by stockmaster** [comment]
This was fixed on the 2.0.2 and RC 2.0.2.1 FYI. but upgrading comes with another full set of headaches....

**Comment by khadkasimon** [comment]
SyntaxError: JSON.parse: unexpected character
OK
<b>Notice</b>: Undefined variable: json in <b>E:\xampp\htdocs\bbstore\admin\controller\sale\order.php</b> on line <b>2490</b>

while updating order status plz help me

**Comment by niyak2** [comment]
lot of issues in opencart ,please test while releasing

**Comment by khadkasimon** [comment]
It's really headache F***k opencart

**Comment by cmario92** [comment]
still having the same issue on 2.0.3.1. Leaving the "Notify Customer" checkbox empty, still notifies the user in any order status change the admin makes.
