### ISSUE TITLE
session(db) write database after database connection close (with my solution)

### ISSUE THREAD

**Issue by shyandsy** [opencart/opencart#5662]
### version 
3.0 release
### configuration
database: mpdo
session: database
### problem
the session db executes SQL after the mpdo::__destruct() called 
```sql
REPLACE INTO SET `data` = 'a:2:{s:8:\"language\";s:5:\"en-gb\";s:8:\"currency\";s:3:\"USD\";}', expire = '2017-07-03 18:23:42' FROM `oc_datou_session` WHERE session_id = 'bfbf4b139b6d0c6eff37ca10ab' AND expire > 1499104782
```

### reason
there is a shutdown callback for request that write session to database
system/library/session/db.php line 18
```
register_shutdown_function('session_write_close');
```

### temporary solution
modify system/library/db/mpdo.php
```php
public function __destruct() {
	$this->connection = null;
}
```
to
```php
public function __destruct() {
	//$this->connection = null;
}
```

the solution is same for other database driver, such as mysqli, postgresql....., 

according to the php documentation, the database will close automatically after all work done.
![image](https://user-images.githubusercontent.com/5271457/27804217-5e995814-5ff3-11e7-975d-95187754bb8e.png)

**Comment by danielkerr** [comment]
this is fixed in the dev branch 3.0.0.1

**Comment by shyandsy** [comment]
@danielkerr 
ok, i will switch to dev branch

may i push my redis driver and config code to dev branch?

**Comment by danielkerr** [comment]
Can do

**Comment by shyandsy** [comment]
@danielkerr 
i swithched to the latest dev version, and the db session still not work!

system/library/session/db.php line 15
```php
public function __construct($registry) {
	$this->db = $registry->get('db');
		
	register_shutdown_function('session_write_close');
	
	$this->expire = ini_get('session.gc_maxlifetime');
}
```

the problem is the parameter passed into the constructor is not $register, instead, is SESSION object

system/library/session.php line 6
```php
public function __construct($adaptor = 'native') {
	$class = 'Session\\' . $adaptor;
		
	if (class_exists($class)) {
		$this->adaptor = new $class($this);    // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!   $this
	} else {
		throw new \Exception('Error: Could not load session adaptor ' . $adaptor . ' session!');
	}		
```

**Comment by shyandsy** [comment]
@danielkerr 
how to push my code to the dev branch?
in another word, how to join your team?

**Comment by danielkerr** [comment]
push to master branch. im going to merge the dev and master. masters for fixes devs for new features

**Comment by danielkerr** [comment]
this is what ur session class should look like

`	public function __construct($adaptor, $registry = '') {
		$class = 'Session\\' . $adaptor;
		
		if (class_exists($class)) {
			if ($registry) {
				$this->adaptor = new $class($registry);
			} else {
				$this->adaptor = new $class();
			}	
			
			register_shutdown_function(array($this, 'close'));
		} else {
			trigger_error('Error: Could not load cache adaptor ' . $adaptor . ' session!');
			exit();
		}	
	}`

**Comment by danielkerr** [comment]
and mine works.

**Comment by danielkerr** [comment]
@shyandsy you need to learn how to use github.

**Comment by shyandsy** [comment]
@danielkerr 
i forgot to switch branch to DEV

**Comment by shyandsy** [comment]
@danielkerr 
is this mean I dont have permission to push to master branch

![image](https://user-images.githubusercontent.com/5271457/27841772-b5018e02-60c9-11e7-9de1-abeb0ac832ff.png)

**Comment by danielkerr** [comment]
doing another quick release for the errors on the upgrade. they were minor last minute changes. shoudl have tested after.

**Comment by danielkerr** [comment]
im not sure what u are saying.

u need to fork the project then when ii have made changes do a pull request.

i need to approve any commits.

**Comment by shyandsy** [comment]
when i do git push, there is an error which said permission  denied to me

**Comment by RaidoDev** [comment]
- first, create a Fork from Opencart, to your account, you will have then:
https://github.com/shyandsy/opencart

- then, clone this shyandsy/opencart repo, make changes. 
- as that will be your "repo" as fork, you will have all permissions.
- when you push changes to *your* repo, you will be able to create pull request into master opencart/opencart.

**Comment by shyandsy** [comment]
@RaidoDev 
 thank u man

**Comment by RaidoDev** [comment]
yw!

**Comment by shyandsy** [comment]
@RaidoDev 
have u see my commit?
https://github.com/shyandsy/opencart/commit/08592fc1c7cef2477f9fa788243a0fba33117a72
