### ISSUE TITLE
Field name required in admin order edit even there is a value.

### ISSUE THREAD

**Issue by moshair** [opencart/opencart#7533]
**What version of OpenCart are you reporting this for?**
3.0.3.2

**Describe the bug**
Disabled custom fields appears in edit order page.
If the custom field is required I get "field name required" even if it has a value.

What section does it affect?
Admin >> Edit Order >> Payment details

**To Reproduce**
First add a custom field in "Custom Fields page" and choose
Custom Field Name = Street
Location = Address
Validation = 
Customer Group = Default
Required = Default
Status = Enabled

1. Go to Admin >> Sales >> Orders >> View Order.
2. Click on 'Edit order'.
3. Click on "->Continue ".
4. See error "field name required" even if it has a value.

**Expected behavior**
Go to Next tap.

**Screenshots / Screen recordings**

![opencart_error_edit_order_admin](https://user-images.githubusercontent.com/13575753/62171924-56a9ff00-b339-11e9-954c-e2bb075e54bd.png)

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? : both
 - Operating system Windows 10 Pro 64bit
 - PHP version: 5.6
 - Apache version : 2.4.25
 - Browser(s) tested with: Firefox
 - Version:  68.0.1 (64bit)

**Additional context**

**Comment by danielkerr** [comment]
will check. i think its been fixed in the master branch already.

**Comment by straightlight** [comment]
Must probably be a related case of this one: https://github.com/opencart/opencart/issues/7023

**Comment by moshair** [comment]
> 
> 
> Must probably be a related case of this one: #7023 but this time might not be about 0 specifically.

Thank you, I didn't use validation regex. It is empty.

Also the other error: Disabled custom fields appears in order edit.

**Comment by straightlight** [comment]
I just found two issues from the master branch. One that checks the custom field status twice (1 from the filter_status and right below recalls the custom field status from the foreach statement) and another one for account_custom_fields where the filter_status is not being used which is where I believe you are referring to from the admin/controller/sale/order.php file which is why disabled fields can still be loaded.

It was discussed prior on the OC forum and this namespace about a 'What about when only admin users wants to add custom fields in the order despite of customers using those fields when they're disabled'. To resolved this issue, Daniel could either decide on it or, as a suggestion, to add an extra row in the admin custom fields page to balance those two logics for the admin users in order to avoid confusion in the future.

**Comment by aaldev** [comment]
Hello! Does anybody fix this issue, because it's still doesn't work Editing order in admin for 3.0.3.2.
All Custom fields show required fields. Thanks in advance

**Comment by straightlight** [comment]
I was able to reproduce the issue during a custom job yesterday. From the OC admin, it does add the custom field but, from the catalog-end, while all the values from, let's say, the register page are added in the oc_customer table, the custom fields are not being added. I checked all array keys and the register controller, as long as the location is implicit, the array does pull the results from the browser once submitting the data.

When adding the data into the database from the addCustomer method, when outputting the array, even with the exit function, it still continues. Which means, this issue is either caused by an event or email transactions that fails to be submitted before site redirection. Even if the events list can be looked at with the eye, it's not enough. Troubleshooting is required to surpass this issue.

**Comment by pemaier** [comment]
**Environment**
Localhost / Linux Debian
OpenCart master from today
PHP 7.4.11
Apache
FireFox 84.0

**Pre-setting - Custom field Flat-No.**
Create custom field (Flat-No.) in Address
Create custom field (Company) in Account

**Test case 1 - Create custom field and order**
Create user with all required entries incl. Flat-No.
Go to Admin Sales and make a new order
Choose the created user as Customer - all fields get filed and go on without error
Choose product
Payment - Choose user - all fields get filed and go on without error
Shipping - Choose user - all fields get filed and go on without error
... 
Order is OK

**Testcase 2 - Create order without predefined user**
Go to Admin Sales and make a new order
Enter new customer data - all fields filed and go on without error
Choose product
Payment - Enter new customer data - all fields filed and get error
![image](https://user-images.githubusercontent.com/10166095/103138910-0a0e5300-46e8-11eb-8351-07dc2496b904.png)


**Additional information**
1. Created Custom fields have field offset difference of -1 on Back-/Frontend
Backend
![image](https://user-images.githubusercontent.com/10166095/103139185-bd784700-46ea-11eb-9024-65ce3752f8dc.png)

Frontend
![image](https://user-images.githubusercontent.com/10166095/103139161-8e61d580-46ea-11eb-8109-3d4fcbd7f1a3.png)

2. Created Custom field is not in the Address list considered
![image](https://user-images.githubusercontent.com/10166095/103139132-522e7500-46ea-11eb-8c1d-3c0d14d5196a.png)

**Comment by danielkerr** [comment]
not bothered about #2.

will check the other one.

**Comment by pemaier** [comment]
I suggest you may consider also situation in testcase #2.
If the problem persists then
a)  it's not possible to create new orders and/or edit orders by the quick (order edit) process e.g. at customer call
b) admins/users get with each order edit task an break in the workflow even if they have to change only e.g. shipping/payment information.
(It's not on me but I would consider this as important because many people use the process in daily work and will get negative attracted on it.)

**Comment by danielkerr** [comment]
all working on the master branch
