### ISSUE TITLE
Bug in opencart custom fields for order edit

### ISSUE THREAD

**Issue by JAY6390** [opencart/opencart#8041]
https://github.com/opencart/opencart/blob/efaadf52df8bc4eba786559d12da0c6003f9b196/upload/admin/view/template/sale/order_form.twig#L2269

The line referenced needs to be changed as the array of elements is 0 based, but the length starts at 1. Fixed code:

```
$('#collapse-customer .form-group').eq($(this).attr('data-sort') - 1).before(this);
```

The fix also needs to be applied to
https://github.com/opencart/opencart/blob/master/upload/admin/view/template/sale/order_form.twig#L2284
and
https://github.com/opencart/opencart/blob/master/upload/admin/view/template/sale/order_form.twig#L2298

Without this, if an elements sort order equals the length of elements, it disappears and produces an error for a field not being set. Setting sort order to 5 does this on a clean install for one custom field

I've not checked elsewhere, but it may happen too on the customer side

**Comment by straightlight** [comment]
Is your reported case about the master branch the fact on using more recent Bootstrap versions where -1 should be added or it happens based on the way jQuery is being used without the -1 and it should? Also, should it also be considered for the pre-release or are you only referring to the master branch version in this case?

More information is needed.

**Comment by JAY6390** [comment]
@straightlight The bug is in the master branch, as I've linked in my post. I've given the buggy code and the solution. It's fairly obvious from there

**Comment by straightlight** [comment]
The reason why I was asking is because, at times, we can identify that identical issues can be found on the pre-release rather than simply the master branch in the mean time, not because your post was not obvious. Presently, I am looking on patching the most relative cases where users identifies those symptoms.

**Comment by JAY6390** [comment]
The issue has been present since April 2015 according to the github blame, and is still there. I don't see why I need to explain this further tbh

**Comment by straightlight** [comment]
> The issue has been present since April 2015 according to the github blame, and is still there. I don't see why I need to explain this further tbh

Well, the following reasons are simple:

1) So that people don't have to wait another 5 years to find out nor to report similar / identical issues.
2) Github Opencart does provide a template for users to fill prior to posting. If explaining further becomes an issue for you at that end, then please post your inquiries on the forum. Otherwise, please follow the template.

**Comment by ivent** [comment]
Hello @JAY6390 , I share here the sadness that problems related to take years to be solved, but I do the work of doing according to the rules and for my happiness or the same has already been corrected in the new version so if the problem has been solved.

https://github.com/opencart/opencart/issues/7979

**Comment by ivent** [comment]
There are going to be two problems with this item or the first was related to an edition of the products that did not go through the address page that was resolved in any previous item, but there is another serious issue that "clears" the customized fields filed when going to the address of delivery during order editing and finally I managed to discover and resolve the error so here’s my contribution:

1- Change making an order click on edit in the last two parts. Note that the custom fields in the field have problems with the Billing Address item and it clears the custom fields in the shipping address to resolve the second point and edit the twing file that has a serious programming error:

> /admin/view/template/sale/order_form.twig

Erro:
A condição do tipo shorthand está incorreta: ([cond] ? [then] ? [else])
O correto é: ([cond] ? [then] : [else])

Change this code

`<input type="text" name="custom_field[{{ custom_field.custom_field_id }}]" value="{{ shipping_custom_field[custom_field.custom_field_id] ? shipping_custom_field[custom_field.custom_field_id] ? custom_field.value }}" placeholder="{{ custom_field.name }}" id="input-shipping-custom-field{{ custom_field.custom_field_id }}" class="form-control" />`

for this code:

`<input type="text" name="custom_field[{{ custom_field.custom_field_id }}]" value="{{ payment_custom_field[custom_field.custom_field_id] ? payment_custom_field[custom_field.custom_field_id] : custom_field.value }}" placeholder="{{ custom_field.name }}" id="input-payment-custom-field{{ custom_field.custom_field_id }}" class="form-control" />`

now Work fine

**Comment by eka7a** [comment]
Fixed
https://github.com/opencart/opencart/commit/f9d853201dd1b713d57bea5f60fe90ff902d7fe8

**Comment by JAY6390** [comment]
@eka7a The "fixed" pull requests do not fix the very issue I mentioned originally, where there needs to be a -1 after the sort values

**Comment by eka7a** [comment]
@JAY6390 sorry. reopened

**Comment by danielkerr** [comment]
this has already been fixed.

**Comment by JAY6390** [comment]
@danielkerr There's no evidence of that in the latest file. The exact code that I mentioned as being the bug

```
$('#collapse-customer .form-group').eq($(this).attr('data-sort')).before(this);
```
is still present in the file and the fix with the `-1` isn't present. The problem line has moved however, it's now line 2275
https://github.com/opencart/opencart/blob/master/upload/admin/view/template/sale/order_form.twig#L2275

**Comment by chufrog** [comment]
Confirm JAY6390 reported issue, the bug still exist on OC 3.X code.

If anyone find this issue up to here, and do not want to modify the code (add that "-1"), a simple workaround is is change the custom field "sort order" value to something bigger, e.g. 80, 81, 82, .... (in case you don't need to add those custom field in between the existing fields...) which can avoid the zero index issue, just don't use the sort index "5" on your custom filed, and your life would be much more easy.
