### ISSUE TITLE
Session Error When Setting Timezone

### ISSUE THREAD

**Issue by bustin98** [opencart/opencart#9237]
**What version of OpenCart are you reporting this for?**
OC 3.0.3.7

**Describe the bug**

Unable to log into the dashboard after changing the timezone from the default of none.

**To Reproduce**

System -> Settings -> Store -> Local -> Time Zone

I set the time zone to America/Detroit (-5:00) and applied the changes. The session ended and was unable to log in.

**Expected behavior**
To be returned to the dashboard with changes applied.

**Screenshots / Screen recordings**
![settings-screen](https://user-images.githubusercontent.com/14907248/107122679-1fd67280-6867-11eb-96b0-1139ac4a80de.jpg)

**Server / Test environment (please complete the following information):**

Local development? Deployed to a web server? - Production server
Operating system - Win2012R2
PHP version - 7.4
Web Server version - IIS8
Browser(s) tested with [e.g. chrome, safari - if applicable] - Chrome

**Extra Notes**

I was able to get out of the situation by changing the session engine from db to file in the system/config/default.php and system/config/catalog.php files.

**Comment by danielkerr** [comment]
it should be something to do with your settings for the server time zone

**Comment by eMintis** [comment]
Working on
Debian 10;
Nginx;
PHP 7.4;
MariaDB 10.5.

**Comment by bustin98** [comment]
I checked my settings in MySQL and I do not have a timezone specified in the configuration. Could that play into how the expiration of sessions is set?

**Comment by lionsgatecreative** [comment]
I'm having the same issue with same version of OC.

**Comment by TheCartpenter** [comment]
According to this forum user: https://forum.opencart.com/viewtopic.php?f=201&t=222369&p=815432#p815421 , the issue seem to have been resolved by applying this solution: https://forum.opencart.com/viewtopic.php?f=201&t=222369&p=815432#p813324 .

**Comment by webkul-dilip** [comment]
> According to this forum user: https://forum.opencart.com/viewtopic.php?f=201&t=222369&p=815432#p815421 , the issue seem to have been resolved by applying this solution: https://forum.opencart.com/viewtopic.php?f=201&t=222369&p=815432#p813324 

@lionsgatecreative @bustin98 Did you still face the same issue?

**Comment by WebkulOpencart** [comment]
I just reinstalled the latest 3.0.3.7 version but not found such an issue so closing this issue

**Comment by ADDCreative** [comment]
@WebkulOpencart This is definitely an issue. Please check it again. It's caused by the fact that the time zone setting is set between reading and writing the session. A negative zone larger than session.gc_maxlifetime will cause the the session read to fail.

It only affects the db session adaptor. It doesn't affect the master as this loads the settings before the session.
https://github.com/opencart/opencart/blob/7738462d64eb726ba75b186ce7ea08938f8e577a/upload/system/config/admin.php#L23-L24

**Comment by WebkulOpencart** [comment]
@ADDCreative I am checking for the -ve time zone again

**Comment by WebkulOpencart** [comment]
@ADDCreative Yes, I found this issue for -ve time zone and working on the same

**Comment by WebkulOpencart** [comment]
@ADDCreative Both the php.ini and MySQL time zone must be the same  as selected in the store setting then this issue will be resolved
please follow this comment here [https://github.com/opencart/opencart/issues/6996#issuecomment-440163494](https://github.com/opencart/opencart/issues/6996#issuecomment-440163494)

**Comment by ADDCreative** [comment]
@WebkulOpencart Then you need to remove the time zone option from the settings. It's pointless it being there if you are saying you need to set the PHP and database time zones manual. It's then just a function the basically does nothing but will just lock admins out if the set a negative value.

**Comment by ADDCreative** [comment]
The broken time zone code in 3.0.3.7 also causes another issue. Even if you change the session engine to file so you can login. You will still have a problem editing orders. https://github.com/opencart/opencart/issues/9492

**Comment by wickedinc** [comment]
This is an issue on a server where resources are shared (pseudo-shared hosting). Not all applications on the system require the timezone to be set to the timezone the server is in.

OS: CentOS 7.7
PHP: 7.3

Changing the timezone to America/New_York prevents login to the admin. This is simple functionality found in a myriad of apps - this should be fixed in the core, and not relying on an underlying system setting.

**Comment by exit15** [comment]
Brand new Server and OC install 
Version | Plesk Obsidian v18.0.39_build1800211014.23 os_Ubuntu 20.04
Plesk Server Time America/New_York

PHP 7.4.25 | Default timezone | America/New_York (I changed it from the default in php.ini)
MySQL "Now ()" shows 2021-10-30 18:59:30 (Current NY Time)
Symptoms:
As soon as I change the timezone from the default UTC to America/New_York in the admin/settings, I am locked out of the system. 
When trying to log in, it goes into some loop as ADDCreative descried which triggered ModSecurity to block my IP
The experience with this install is far from normal. Reading the forum, I could not fine a clear solution.
What should I do here?

**Comment by dabbmedia** [comment]
`UPDATE oc_setting s SET s.`value` = 'Africa/Abidjan' WHERE s.`code` = 'config' AND s.`key` = 'config_timezone' LIMIT 1;`

will allow you to login again.

Consider leaving the date-times to UTC, then format them for display in the correct time zone:

`"now"|date("H:i", "America/New_York")` or `{{ date_added|date("H:i", "America/New_York") }}`

The issue is a known bug, not yet fixed.

**Comment by dabbmedia** [comment]
@exit15 you can restart apache to stop the loop, if that continues.

You can also check the domain's apache access logs, to verify there's not an actual brute force attempt in progress.

**Comment by ADDCreative** [comment]
Change date_timezone in system/config/default.php to match the timezone you set in the settings.
https://github.com/opencart/opencart/blob/3.0.3.8/upload/system/config/default.php#L14

This should allow you to use a different time zone and still login.

**Comment by exit15** [comment]
Thanks @ADDCreative. I change system/config/default.php line 14 to America/New_York and it did the trick. 
Also, I restored the default value "; date.timezone = " in php.ini. as in my case the server time is set to America/New_York
 
Basically only only needs to set the system/config/default.php timezone to be the same as the value selected in the admin / settings / local / timezone

**Comment by TBrannon** [comment]
This issue still exists in 3.0.3.8.  Fresh install, Change only the system time from UTC to American/Chicago and was not able to log in after being kicked out.
As per @ADDCreative comment above changed the UTC value in system/config/default.php to America/Chicago and was able to log in immediately.

**Comment by msjbo** [comment]
nice,solved well!!

**Comment by mhcwebdesign** [comment]
@Pat043 : Have you tried this fix: https://github.com/opencart/opencart/pull/13704 ?
