### ISSUE TITLE
Can't receive normal html content email 3.0.3.7

### ISSUE THREAD

**Issue by evaland999** [opencart/opencart#9385]
Sending email using default settings via mail() in PHP 8.

Message is like:
------=_NextPart_10f35f1c84da9c502da0c116e7c79d9d
Content-Type: multipart/alternative; boundary="----=_NextPart_10f35f1c84da9c502da0c116e7c79d9d_alt"

------=_NextPart_10f35f1c84da9c502da0c116e7c79d9d_alt
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: 8bit

This is a HTML email and your email client software does not support HTML email!
------=_NextPart_10f35f1c84da9c502da0c116e7c79d9d_alt
Content-Type: text/html; charset="utf-8"
Content-Transfer-Encoding: 8bit

Using SMTP() works normal.

Dear danielkerr ,
So sorry bother your time,But I got the same issue.
I using 3.0.3.7,
PHP8.0
I made a simple video to show how problem,if you can please check it
I spent many days try to figure out how to fix,But fail

https://youtu.be/wMrzL1Kqqgo

**Comment by condor2** [comment]
This issue was reported, but closed :)

https://github.com/opencart/opencart/issues/8968

**Comment by evaland999** [comment]
May I report more about this issue.
According My test.
This issue happened when using "Mail" in settings of opencart's admin.
When I choice "SMTP" in settings of opencart's admin.
I mean I switch to use the SMTP of my server's (such as mail.xxx.com).
This problem never happened.
I don't know why cause this problem,Maybe PHP8.0 or some other reasons else.

By the way,My live shop is using 2.0.2,It's very old I know,
But this problem never happened.

I really hope some kind and great developer fellows can help fix

**Comment by evaland999** [comment]
I check out
The info of sender wrong either.
In normal situation,
when get the email from OC(such as send order status to customer)
Then customer should see hear of email is "store name" and the store's email
But they not,
Customer see the name of "email server"

**Comment by evaland999** [comment]
Early I downloaded the Master version of OC(4.000b) to test.
Using server's Mail of Mail Engine
to test register a account in front end page
but still get the wrong email
https://www.evaland.com.tw/maxtest/

Wrong email contents

------=_NextPart_feaad1d2c5af66a0e580c7e02d643891
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: base64

V2VsY29tZSBhbmQgdGhhbmsgeW91IGZvciByZWdpc3RlcmluZyBhdCBZb3VyIFN0b3JlIQoKWW91ciBhY2NvdW50IGhhcyBub3cgYmVlbiBjcmVhdGVkIGFuZCB5b3UgY2FuIGxvZyBpbiBieSB1c2luZyB5b3VyIGVtYWlsIGFkZHJlc3MgYW5kIHBhc3N3b3JkIGJ5IHZpc2l0aW5nIG91ciB3ZWJzaXRlIG9yIGF0IHRoZSBmb2xsb3dpbmcgVVJMOgoKaHR0cHM6Ly93d3cuZXZhbGFuZC5jb20udHcvbWF4dGVzdC9pbmRleC5waHA/cm91dGU9YWNjb3VudC9sb2dpbiZsYW5ndWFnZT1lbi1nYgoKVXBvbiBsb2dnaW5nIGluLCB5b3Ugd2lsbCBiZSBhYmxlIHRvIGFjY2VzcyBvdGhlciBzZXJ2aWNlcyBpbmNsdWRpbmcgcmV2aWV3aW5nIHBhc3Qgb3JkZXJzLCBwcmludGluZyBpbnZvaWNlcyBhbmQgZWRpdGluZyB5b3VyIGFjY291bnQgaW5mb3JtYXRpb24uCgpUaGFua3MsCllvdXIgU3RvcmUK
------=_NextPart_feaad1d2c5af66a0e580c7e02d643891--
![wrongcontents](https://user-images.githubusercontent.com/79344209/109381043-de3f6180-7912-11eb-90ee-ab7a9dbf4fd9.JPG)

**Comment by evaland999** [comment]
Hi every body.
I have made sure the "can't receive normal html "email,
Only happened on PHP 8.0
I tested on PHP7.3 this problem never happened again.I mean all email can read very correct.

Can any good fellows can help fix the issue when usinf PHP8.0

**Comment by prabhatkumaroc082** [comment]
@evaland999 
I registered on your website https://www.evaland.com.tw/max/ but did not get any issue on mail.

**Comment by prabhatkumaroc082** [comment]
If you are using any modification then try disabling it.

**Comment by evaland999** [comment]
> 
> 
> If you are using any modification then try disabling it.

You can receive normal html content's email(such as register account),
that's because I switch Mail Engine to "SMTP" not "Mail",please check my screentshot image.
These days I have tested a lot,
I very sure the problem of email content not correct,it's because 3.0.3.7 install on PHP8.0.
this problem not happened on PHP7.3 or 7.4

When you saw my conclusion above,Maybe you will said"Then just use SMTP,the issued won't happen again"
But the ugly is"Many extensions still use "Mail" with it's default mail setting,Even I switch to SMTP in the setting of admin,
I believe many extensions will have the problem happened.


So the final solution is
1.Make 3.0.3.7 or 3.0.3.xx to full support PHP8
2.Or ask user of 3.0.3.7 or 3.0.3.xx just only use PHP 7.3 or 7.4
But if so,will lose many performance of PHP 8.0
3.Or waiting OC 4.xx can release soon.
![smtp](https://user-images.githubusercontent.com/79344209/109463987-e927fc80-7aa0-11eb-9c11-34f0f2ad7722.JPG)

**Comment by condor2** [comment]
There is no more interest for 3.0.x.x...

For example

https://github.com/opencart/opencart/issues/8272#issuecomment-758460834

**Comment by evaland999** [comment]
> 
> 
> There is no more interest for 3.0.x.x...
> 
> For example
> 
> [#8272 (comment)](https://github.com/opencart/opencart/issues/8272#issuecomment-758460834)
> 
> Or this...
> #9256

Pardon me,But I  a just a senior user of OC, I don’t know how to write or modify the core of OC.
Would you mind explain more clear about you just replied

**Comment by condor2** [comment]
As I said. There is no interest in 3.0.x.x.
Daniel work only on Master Branch.

**Comment by evaland999** [comment]
> 
> 
> As I said. There is no interest in 3.0.x.x.
> Daniel work only on Master Branch.

I have also realized this situation in the past few days ,
But it's not bad,Just hope OC 4.xx can release soon.
Do you know when possible OC 4.xx can release.

**Comment by condor2** [comment]
In my opinion as normal user, possible after 6 months.

**Comment by evaland999** [comment]
> 
> 
> In my opinion as normal user, possible after 6 months.

According to your understanding ,Do you know OC3.xxx can upgrade to OC4.xx or not.

**Comment by condor2** [comment]
I didn't tested but should work when is released.

**Comment by evaland999** [comment]
> 
> 
> I didn't tested but should work when is released.

Building a whole new and latest version of OC is my first priority plan this year.
Because My live shop is using OC 2.0.2,you can understand it's too old and too "slow"
Since I plan install a whole new shopping system.
In my Highest expectations is :Latest OC with Latest PHP,I tested it PHP8.0 really support much faster performance .

**Comment by condor2** [comment]
You can test Master Branch to see if have same mail issue.

**Comment by evaland999** [comment]
> 
> 
> You can test Master Branch to see if have same mail issue.

In fact I have download Master Branch today early and try install it.
But it's have error on install page.
https://www.evaland.com.tw/maxtest/install/
![install](https://user-images.githubusercontent.com/79344209/109468985-6145f080-7aa8-11eb-91dc-2d4da5e585e7.JPG)

**Comment by condor2** [comment]
Download again and will work.

**Comment by evaland999** [comment]
> 
> 
> Download again and will work.

Pardon me,
I download from
https://github.com/opencart/opencart/archive/master.zip
and then upload it to my server then Go through the normal installation procedure .
1.copy all the files in upload on Master branch folder to /maxtest folder
2.rename config.php
3.run https://www.evaland.com.tw/maxtest/install/
But still get the same error page.
Do I miss something or do wrong action
![install](https://user-images.githubusercontent.com/79344209/109470766-d1557600-7aaa-11eb-8fbf-f1dd6b772e65.JPG)

**Comment by condor2** [comment]
Work just fine for me.

**Comment by evaland999** [comment]
> 
> 
> Work just fine for me.

Would you like to test on my site.
| Domain: evaland.com.tw
evaland.com.tw
| UserName: evalandcom
| PassWord: sGlV6fx{2IWK
must use SFTP mode

**Comment by evaland999** [comment]
folder is in the maxtest

**Comment by condor2** [comment]
Delete connection data. I will upload again.

**Comment by evaland999** [comment]
> 
> 
> Delete connection data. I will upload again.

seems missing
require_once(DIR_SYSTEM . 'startup.php');

**Comment by condor2** [comment]
Uploading not finished. Low speed.

**Comment by evaland999** [comment]
> 
> 
> Uploading not finished. Low speed.

it's ok,
please tell me again when upload done.
Can't wait to test

**Comment by condor2** [comment]
I think is something wrong with your server settings. Error 404 on index.php...

**Comment by evaland999** [comment]
> 
> 
> I think is something wrong with your server settings. Error 404 on index.php...

I not sure,
My server is using PHP 8.0
And not special setting in it.

**Comment by evaland999** [comment]
I checkout opencart-master.zip
in the folder of isntall not a file named startup.php

**Comment by condor2** [comment]
Change php to 7.4 for a second.

**Comment by evaland999** [comment]
> 
> 
> Change php to 7.4 for a second.

Do you mean change PHP from 8.0 to 7.4 and reinstall Master Branch?
If yes,I just did it early,But show error 
"only support PHP 8.0"
I mean the simple alert text show in the Left top corner.

**Comment by evaland999** [comment]
> 
> 
> > Change php to 7.4 for a second.
> 
> Do you mean change PHP from 8.0 to 7.4 and reinstall Master Branch?
> If yes,I just did it early,But show error
> "only support PHP 8.0"
> I mean the simple alert text show in the Left top corner.

Let me made a video to show you

**Comment by condor2** [comment]
Yes, just change from 8.0 to 7.4 then I will make to work on php 7.4

**Comment by evaland999** [comment]
> 
> 
> Yes, just change from 8.0 to 7.4 then I will make to work on php 7.4

Sir,would you mind check this video first
https://youtu.be/zvQ6EWHC_1k

**Comment by condor2** [comment]
Change back to php 8.0 and contact server support because php files are not rendered when is 8.0.

**Comment by evaland999** [comment]
> 
> 
> Change back to php 8.0 and contact server support because php files are not rendered when is 8.0.

Pardon me sir.
What's mean about "files are not rendered when is 8.0"

**Comment by condor2** [comment]
Failed to load resource: the server responded with a status of 404 (Not Found) for index.php

**Comment by evaland999** [comment]
> 
> 
> Failed to load resource: the server responded with a status of 404 (Not Found) for index.php

Thanks for the tips up Sir.
I am contact the server administrator now.But on USA still very early,I need wait them on work.
Allow me report you later.

**Comment by condor2** [comment]
I think PHP 8.0 isn't fully implemented on your server.

**Comment by evaland999** [comment]
> 
> 
> I think PHP 8.0 isn't fully implemented on your server.

Hi,I contact my server support,He said my PHP 8.0 full function.
May I ask you where to find startup.php in the folder of master branch

**Comment by condor2** [comment]
Ask them why installer doesn'r load with PHP 8.0. 
Give them this link

https://www.evaland.com.tw/maxtest/install/

Startup is here
https://github.com/opencart/opencart/tree/master/upload/system

**Comment by evaland999** [comment]
> 
> 
> Ask them why installer doesn't work with PHP 8.0.
> Give them this link
> 
> https://www.evaland.com.tw/maxtest/install/
> 
> Startup is here
> https://github.com/opencart/opencart/tree/master/upload/system

Hi,Early Server support reply me about it.
They said my server's PHP8.0 is running well
https://evaland.com.tw/phpinfo.php
Can you help check

**Comment by condor2** [comment]
As I said.
Better ask again why this page doesn't load on PHP 8.0

https://www.evaland.com.tw/maxtest/install/

Give them that link

**Comment by condor2** [comment]
Now you can install it.

**Comment by evaland999** [comment]
> 
> 
> Now you can install it.
> 
> Was because of this
> 
> https://github.com/opencart/opencart/pull/9390/files

Thank you sir,
Pardon me,May I ask more clear.
Do you mean I download from 
https://github.com/opencart/opencart/archive/master.zip
and then upload and install it again.

**Comment by condor2** [comment]
Just install it.

**Comment by evaland999** [comment]
> 
> 
> Just install it.

Dear sir,Thanks again for helping me.
I just did installed it again ,And this time can install success
But then I link to
https://www.evaland.com.tw/maxtest/admin/
and get the error
TypeError: Opencart\System\Engine\Registry::get(): Return value must be of type object, string returned in /home/evalandcom/public_html/maxtest/system/engine/registry.php on line 25

Do you know why cause this?

**Comment by prabhatkumaroc082** [comment]
fix for 3.0.3.7 #9358

**Comment by evaland999** [comment]
> 
> 
> fix for 3.0.3.7 #9358

Dear prabhatkumaroc082:
Pardon me,But I not code expert,
In fact I just a senior user of used OC many years.
Do you mean about OC 3.0.3.7 can't send out normal mail When using PHP8.xx.
Does this issue have fixed.
If yes,can you tell me which patch files I can download to upgrade.
Thank you very much sir.

**Comment by prabhatkumaroc082** [comment]
@evaland999 
The changes are not merged yet, under testing. Please try to apply https://github.com/opencart/opencart/pull/9358/commits/7ccd255a425e36dd19a4123c83e83cb08aa429ff commit changes.

**Comment by evaland999** [comment]
> 
> 
> @evaland999
> The changes are not merged yet, under testing. Please try to apply [7ccd255](https://github.com/opencart/opencart/commit/7ccd255a425e36dd19a4123c83e83cb08aa429ff) commit changes.

Dear  prabhatkumaroc082 
Thank you very much,The mail issue fixed,Now I can use PHP 8.xx
Pardon me again sir.
Does this issue fixed also on OC 4.xx.

**Comment by prabhatkumaroc082** [comment]
@evaland999 
I have not performed testing on V4 but you should not face such mail issue on OC4 also.

**Comment by prabhatkumaroc082** [comment]
> > @evaland999
> > The changes are not merged yet, under testing. Please try to apply [7ccd255](https://github.com/opencart/opencart/commit/7ccd255a425e36dd19a4123c83e83cb08aa429ff) commit changes.
> 
> Dear prabhatkumaroc082
> Thank you very much,The mail issue fixed,Now I can use PHP 8.xx
> Pardon me again sir.
> Does this issue fixed also on OC 4.xx.

Yes, It seems the issue is fixed now, the changes will go to the maintenance branch soon after testing on PHP 8 and lower versions. Also, you should not face the same on oc4.x.

**Comment by ADDCreative** [comment]
@WebkulOpencart Might want to make the same changes to smtp.php so it's consistent with mail.php and the master branch, https://github.com/opencart/opencart/pull/7409

**Comment by evaland999** [comment]
Dear Sir,
So sorry trouble you again
About the issue of PHP8 compatible mail 
Seems can't receive normal html email contents again.
I am using OC 3.0.3.7 and PHP 8.xx
Can you help to fix it

**Comment by prabhatkumaroc082** [comment]
> Dear prabhatkumaroc082
> Thank you very much,The mail issue fixed,Now I can use PHP 8.xx
> Pardon me again sir.
> Does this issue fixed also on OC 4.xx.

You had confirmed for issue fixation. Please verify the changes again, because it is not faced now.

**Comment by evaland999** [comment]
> 
> 
> > Dear prabhatkumaroc082
> > Thank you very much,The mail issue fixed,Now I can use PHP 8.xx
> > Pardon me again sir.
> > Does this issue fixed also on OC 4.xx.
> 
> You had confirmed for issue fixation. Please verify the changes again, because it is not faced now.

[mail.zip](https://github.com/opencart/opencart/files/6257140/mail.zip)
Dear Sir,
Please forgive my stupid,
I download the mail.php from github.com and uploaded it to my 3.0.3.7
and then tested it again 
but issue still there.
Sir,I really don't know how to fix it well
can you help check,I can give you my server info  and OC login info
Or can you teach me again.

**Comment by prabhatkumaroc082** [comment]
@evaland999 
Duplicate issue https://github.com/opencart/opencart/issues/9551
